# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: node_js
node_js:
  - "node"
  - "7"
  - "6"


env:

notifications:
  email:
    on_success: change
    on_failure: change
