# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: node_js
node_js:
  - "node"
  - "8"


env:
  global:
    - CC_TEST_REPORTER_ID=5cd93a6f008add74a23f24e343c6857d47b0d3905ddeeff24371510d13bc30f5

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  # download code climate reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./node_modules/.bin/tap --coverage-report=lcov &&  ./cc-test-reporter after-build  -t lcov --exit-code $TRAVIS_TEST_RESULT
