# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: node_js
node_js:
  - "node"
  - "8"


env:

addons:
  code_climate:
    repo_token: 5cd93a6f008add74a23f24e343c6857d47b0d3905ddeeff24371510d13bc30f5

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - npm install codeclimate-test-reporter
  - ./node_modules/.bin/tap --coverage-report=text-lcov | ./node_modules/.bin/codeclimate-test-reporter
