# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: node_js
node_js:
  - "node"
  - "7"
  - "6"


env:
  CODECLIMATE_REPO_TOKEN: 8320bf7b177ff7583cc3fcc203d8200155ffa184f7731172cd227be22d0e27ff

notifications:
  email:
    on_success: change
    on_failure: change
